/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SiyeViewer {
    }
}
declare global {
    interface HTMLSiyeViewerElement extends Components.SiyeViewer, HTMLStencilElement {
    }
    var HTMLSiyeViewerElement: {
        prototype: HTMLSiyeViewerElement;
        new (): HTMLSiyeViewerElement;
    };
    interface HTMLElementTagNameMap {
        "siye-viewer": HTMLSiyeViewerElement;
    }
}
declare namespace LocalJSX {
    interface SiyeViewer {
    }
    interface IntrinsicElements {
        "siye-viewer": SiyeViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "siye-viewer": LocalJSX.SiyeViewer & JSXBase.HTMLAttributes<HTMLSiyeViewerElement>;
        }
    }
}
